#!/usr/bin/env bash
# build.sh - Build Unify Desktop Assistant .pkg Package (macOS)
#
# This script assembles the .pkg installer for Unify Desktop Assistant.
# It packages pre-built magnitude and agent-service alongside the tools,
# GUI, launchd templates, and installer scripts.
#
# Uses pkgbuild + productbuild (Xcode command-line tools, ships with macOS).
#
# Usage:
#   ./build.sh                  # Build .pkg (production URLs)
#   ./build.sh --staging        # Build .pkg (staging URLs)
#   ./build.sh --version 1.2.0  # Build with custom version
#   ./build.sh --clean          # Clean output before building

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_DIR="$SCRIPT_DIR/output"
BUILD_DIR="$SCRIPT_DIR/build"

# Package identifier
PKG_ID="ai.unify.desktop-assistant"

# Defaults
VERSION="1.0.0"
STAGING=false
CLEAN=false
ENVIRONMENT="main"

# Environment-specific URLs
ORCHESTRA_URL_MAIN="https://api.unify.ai/v0"
ORCHESTRA_URL_STAGING="https://internal.example.com/v0"
COMMS_URL_MAIN="https://service.a.run.app"
COMMS_URL_STAGING="https://service.a.run.app"

echo ""
echo "=========================================="
echo "  Unify Desktop Assistant - Build .pkg"
echo "=========================================="
echo ""

# =============================================================================
# Argument Parsing
# =============================================================================

while [[ $# -gt 0 ]]; do
    case "$1" in
        --version)
            VERSION="$2"; shift 2 ;;
        --staging)
            STAGING=true; ENVIRONMENT="staging"; shift ;;
        --clean)
            CLEAN=true; shift ;;
        -h|--help)
            echo "Usage: $(basename "$0") [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --version VER   Set package version (default: 1.0.0)"
            echo "  --staging       Build with staging URLs"
            echo "  --clean         Clean output before building"
            echo "  -h, --help      Show this help"
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

# =============================================================================
# Clean
# =============================================================================

if $CLEAN; then
    echo "Cleaning build directories..."
    rm -rf "$OUTPUT_DIR" "$BUILD_DIR"
    echo "  Cleaned"
fi

# =============================================================================
# Validate Prerequisites
# =============================================================================

echo "Checking prerequisites..."

if ! command -v pkgbuild &>/dev/null; then
    echo "ERROR: pkgbuild not found. Install Xcode Command Line Tools:" >&2
    echo "  xcode-select --install" >&2
    exit 1
fi

if ! command -v productbuild &>/dev/null; then
    echo "ERROR: productbuild not found. Install Xcode Command Line Tools:" >&2
    echo "  xcode-select --install" >&2
    exit 1
fi

if [[ ! -f "$PROJECT_DIR/magnitude/package.json" ]]; then
    echo "ERROR: magnitude/package.json not found at $PROJECT_DIR/magnitude/" >&2
    echo "  Make sure magnitude is checked out in the macos/ directory." >&2
    exit 1
fi

if [[ ! -f "$PROJECT_DIR/agent-service/package.json" ]]; then
    echo "ERROR: agent-service/package.json not found at $PROJECT_DIR/agent-service/" >&2
    exit 1
fi

echo "  Prerequisites OK"

# =============================================================================
# Prepare Build Tree
# =============================================================================

echo "Preparing build tree..."

rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR/payload/opt/unify-desktop-assistant"
mkdir -p "$BUILD_DIR/payload/usr/local/bin"
mkdir -p "$BUILD_DIR/scripts"

APP_ROOT="$BUILD_DIR/payload/opt/unify-desktop-assistant"

# --- Environment-specific URL baking ---
if $STAGING; then
    ORCHESTRA_URL="$ORCHESTRA_URL_STAGING"
    COMMS_URL="$COMMS_URL_STAGING"
    echo "  Environment: staging"
else
    ORCHESTRA_URL="$ORCHESTRA_URL_MAIN"
    COMMS_URL="$COMMS_URL_MAIN"
    echo "  Environment: main (production)"
fi

cat > "$APP_ROOT/environment.conf" <<EOF
# Auto-generated by build.sh — do not edit
# Environment: $ENVIRONMENT
ORCHESTRA_URL=$ORCHESTRA_URL
UNITY_COMMS_URL=$COMMS_URL
EOF
echo "  Baked environment.conf ($ENVIRONMENT)"

# --- tools/ ---
echo "  Copying tools/..."
mkdir -p "$APP_ROOT/tools"
cp "$PROJECT_DIR/tools/setup.sh" "$APP_ROOT/tools/"
# launchd entrypoints execed by the agents at runtime (websockify, agent, sftp).
cp "$PROJECT_DIR/tools/"run-*.sh "$APP_ROOT/tools/" 2>/dev/null || true
chmod +x "$APP_ROOT/tools/setup.sh"
chmod +x "$APP_ROOT/tools/"run-*.sh 2>/dev/null || true

# --- gui/ ---
echo "  Copying gui/..."
mkdir -p "$APP_ROOT/gui"
if [[ -f "$PROJECT_DIR/gui/unify-assistant.py" ]]; then
    cp "$PROJECT_DIR/gui/unify-assistant.py" "$APP_ROOT/gui/"
    chmod +x "$APP_ROOT/gui/unify-assistant.py"
fi

# --- assets/ (tray logo, etc.) ---
echo "  Copying assets/..."
mkdir -p "$APP_ROOT/assets"
cp "$PROJECT_DIR/assets/"* "$APP_ROOT/assets/" 2>/dev/null || true

# --- launchd/ ---
echo "  Copying launchd templates..."
mkdir -p "$APP_ROOT/launchd"
cp "$PROJECT_DIR/launchd/"*.plist "$APP_ROOT/launchd/" 2>/dev/null || true

# --- magnitude/ (excluding node_modules, .git) ---
echo "  Copying magnitude/ (excluding node_modules, .git)..."
mkdir -p "$APP_ROOT/magnitude"
tar -C "$PROJECT_DIR/magnitude" \
    --exclude='node_modules' --exclude='.git' --exclude='*.log' \
    -cf - . | tar -C "$APP_ROOT/magnitude" -xf -

# --- agent-service/ (excluding node_modules, .git, .env, logs) ---
echo "  Copying agent-service/ (excluding node_modules, .git, .env, logs)..."
mkdir -p "$APP_ROOT/agent-service"
tar -C "$PROJECT_DIR/agent-service" \
    --exclude='node_modules' --exclude='.git' --exclude='.env' --exclude='*.log' \
    -cf - . | tar -C "$APP_ROOT/agent-service" -xf -

# --- logs/ directory ---
mkdir -p "$APP_ROOT/logs"

# --- CLI wrapper ---
echo "  Installing CLI wrapper..."
cp "$PROJECT_DIR/usr/bin/unify-desktop-assistant" "$BUILD_DIR/payload/usr/local/bin/unify-desktop-assistant"
chmod 755 "$BUILD_DIR/payload/usr/local/bin/unify-desktop-assistant"

# --- Installer scripts ---
echo "  Copying installer scripts..."
cp "$SCRIPT_DIR/scripts/preinstall" "$BUILD_DIR/scripts/preinstall"
cp "$SCRIPT_DIR/scripts/postinstall" "$BUILD_DIR/scripts/postinstall"
chmod 755 "$BUILD_DIR/scripts/preinstall"
chmod 755 "$BUILD_DIR/scripts/postinstall"

# --- Set permissions ---
echo "  Setting permissions..."
find "$BUILD_DIR/payload" -type d -exec chmod 755 {} \;
find "$APP_ROOT" -name "*.sh" -exec chmod 755 {} \;
find "$APP_ROOT" -name "*.py" -exec chmod 755 {} \;

# =============================================================================
# Build .pkg Package
# =============================================================================

echo ""
echo "Building .pkg package..."

mkdir -p "$OUTPUT_DIR"

ENV_SUFFIX=""
if $STAGING; then
    ENV_SUFFIX="-staging"
fi

COMPONENT_PKG="$BUILD_DIR/component.pkg"
FINAL_PKG="$OUTPUT_DIR/unify-desktop-assistant_${VERSION}${ENV_SUFFIX}_macos.pkg"

# Step 1: Build component package
pkgbuild \
    --root "$BUILD_DIR/payload" \
    --scripts "$BUILD_DIR/scripts" \
    --identifier "$PKG_ID" \
    --version "$VERSION" \
    --install-location "/" \
    "$COMPONENT_PKG"

# Step 2: Generate distribution XML (adds Welcome / Conclusion panes)
DIST_XML="$BUILD_DIR/distribution.xml"
cat > "$DIST_XML" <<DISTXML
<?xml version="1.0" encoding="utf-8"?>
<installer-gui-script minSpecVersion="2">
    <title>Unify Desktop Assistant</title>
    <welcome file="welcome.html" mime-type="text/html"/>
    <conclusion file="conclusion.html" mime-type="text/html"/>
    <options customize="never" require-scripts="false" hostArchitectures="arm64,x86_64"/>
    <choices-outline>
        <line choice="default">
            <line choice="$PKG_ID"/>
        </line>
    </choices-outline>
    <choice id="default"/>
    <choice id="$PKG_ID" visible="false">
        <pkg-ref id="$PKG_ID"/>
    </choice>
    <pkg-ref id="$PKG_ID" version="$VERSION" onConclusion="none">component.pkg</pkg-ref>
</installer-gui-script>
DISTXML

# Step 3: Wrap with productbuild using the distribution + resources
productbuild \
    --distribution "$DIST_XML" \
    --resources "$SCRIPT_DIR/resources" \
    --package-path "$BUILD_DIR" \
    "$FINAL_PKG"

# =============================================================================
# Summary
# =============================================================================

echo ""
echo "Build complete!"
echo ""
echo "Output files:"
PKG_SIZE=$(du -sh "$FINAL_PKG" 2>/dev/null | cut -f1)
echo "  $(basename "$FINAL_PKG") ($PKG_SIZE)"
echo ""
echo "Install with:"
echo "  sudo installer -pkg $FINAL_PKG -target /"
echo ""
echo "Or double-click the .pkg file in Finder."
echo ""

# Cleanup build directory
rm -rf "$BUILD_DIR"
echo "Build tree cleaned up."
